[theme]
primaryColor="#4CAF50"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[server]
port = 8501
headless = true
enableCORS = false
enableWebsocketCompression = false

[browser]
serverAddress = "0.0.0.0"  # Listen on all interfaces
